[project]
name = "tiktok-alerts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.0",
    "python-telegram-bot[job-queue]>=22.2",
    "requests>=2.32.4",
    "uvicorn>=0.35.0",
]
